NAME = libft.a
COMPILER = cc
COMPILERFLAGS = -Wall -Wextra -Werror
SRCS = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
		ft_strlen.c ft_memset.c ft_bzero.c \
OBJS = $(SRCS:.c = .o)

all : 